version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mojabaza

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
